server:
  port: 8080
  servlet:
    context-path: /provider
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.211.128:3306/mysql
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource


mybatis-plus:
  type-aliases-package: com.wang.pojo




